In [1]:
#import numpy

import numpy as np

In [2]:
my_lst=[1,2,3]
arr=np.array(my_lst)

In [3]:
type(arr)

numpy.ndarray

In [4]:
print(arr)

[1 2 3]


In [5]:
arr.shape

(3,)

In [6]:
##Multilisted array

my_lst1=[1,2,3,4]
my_lst2=[2,3,4,5]
my_lst3=[6,5,4,3]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [7]:
print(arr)

[[1 2 3 4]
 [2 3 4 5]
 [6 5 4 3]]


In [8]:
type(arr)

numpy.ndarray

In [9]:
arr

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [6, 5, 4, 3]])

In [10]:
arr.data

In [11]:
arr.dtype

dtype('int32')

In [12]:
arr.shape

(3, 4)

In [13]:
arr.reshape(4,3)

array([[1, 2, 3],
       [4, 2, 3],
       [4, 5, 6],
       [5, 4, 3]])

In [14]:
arr[0:2,:]

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [15]:
arr[:,1]

array([2, 3, 5])

In [16]:
arr[1:2,1:]

array([[3, 4, 5]])

In [19]:
arr=np.arange(0,10)

In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr[3:]=100

In [22]:
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])